version: 2.1

jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify

  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=release

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=release

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=debug

  generate-documentation-pr-for-main-dot-actor:
    docker:
      - image: ponylang/main.actor-ci:standard
    steps:
      - checkout
      - run: bash .ci-scripts/upload-release-documentation-to-main-actor.bash "$CIRCLE_TAG" "${GITHUB_ACCESS_TOKEN_NAME}"

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=debug

workflows:
  version: 2.1
  on-every-commit:
    jobs:
      - verify-changelog
      - release-vs-ponyc-release
      - debug-vs-ponyc-release

  on-release-being-tagged:
    jobs:
      - generate-documentation-pr-for-main-dot-actor:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

  daily-check-for-breakage:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master
      - debug-vs-ponyc-master
